services:
  firebase:
    image: goatlab/firebase-emulator:1.2-arm64
    container_name: emulator
    ports:
      - "9199:9199"
      - "4000:4000"
      - "8090:8090"
    command: ["firebase", "emulators:start", "--only", "storage,logging", "--project", "fir-demo-project", '--config', "./startfirebase.json"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "localhost:4400/emulators"]
      interval: 10s
      start_period: 10s
      retries: 3
      timeout: 5s
  test-docker:
    build:
      dockerfile: Dockerfile
      context: apps/docker
    container_name: allure-docker
#    env_file: .env.slack
    environment:
      FIREBASE_STORAGE_EMULATOR_HOST: 127.0.0.1:9199 # Dev mode
      STORAGE_BUCKET: $GCP_BUCKET
      PREFIX: 'project-999'
      REPORT_NAME: 'Demo Report 1'
      SHOW_HISTORY: false
      RETRIES: 5
    volumes:
      - ./key.json:/credentials/key.json:ro
      - ./assets/allure-results:/allure-results
    cpus: 1
    mem_limit: 2048m
    network_mode: service:firebase
    depends_on:
      firebase:
        condition: service_healthy
  test-cli:
    build:
      context: apps/cli
      dockerfile: test.Dockerfile
    container_name: allure-cli
    environment:
      CI: 'true'
    tty: false
    command: ['sh', '-c', 'allure-deployer deploy /allure-results --gcp-json /key.json --bucket $GCP_BUCKET']
    volumes:
      - ./assets/allure-results:/allure-results
      - ./key.json:/key.json:ro
  test-action:
    image: act-github-actions-dockeraction:latest
    build:
      context: apps/action
      dockerfile: action.Dockerfile


