services:
  storage:
    image: oittaa/gcp-storage-emulator
    container_name: storage-emulator
    env_file: .env
    environment:
      PORT: 9023
      HOST: localhost
    ports:
      - "9023:9023"
    restart: unless-stopped
    entrypoint: ["gcp-storage-emulator", "start", "--default-bucket", "gatedaccessdev.appspot.com"]
    volumes:
      - "${PWD}/cloudstorage:/storage"
    healthcheck:
      test: ["CMD", "gcp-storage-emulator", "--help"]
      interval: 10s
      start_period: 10s
      retries: 3
      timeout: 5s
  test-docker:
    build:
      dockerfile: test.Dockerfile
      context: apps
    container_name: allure-docker
    env_file: .env
    volumes:
      - ./key.json:/credentials/key.json:ro
      - ./assets/allure-results:/allure-results
    cpus: 1
    mem_limit: 2048m
    network_mode: service:storage
    depends_on:
      storage:
        condition: service_healthy


