name: 'Allure Deployer Action'
description: 'Deploy Allure Reports as a website, with unique Ephemeral URLs per report and notification to Slack, No server required'
author: 'Sokari Gillis-Harry'
runs:
  using: 'docker'
  image: 'test.Dockerfile'
#  image: 'docker://sokari/allure-deployer-action:latest'
  args:
    - storage_bucket=${{ inputs.storage_bucket }}
    - report_name=${{ inputs.report_name }}
    - slack_channel=${{ inputs.slack_channel }}
    - allure_results_path=${{ inputs.allure_results_path }}
    - retries=${{ inputs.retries }}
    - show_history=${{ inputs.show_history }}
    - prefix=${{ inputs.prefix}}
    - update_pr=${{inputs.update_pr}}

inputs:
  storage_bucket:
    description: 'Google Cloud Storage bucket name'
    required: true
  report_name:
    description: 'Name/Title of your report'
    required: false
    default: 'Allure Report'
  slack_channel:
    description: 'Slack channel ID for notifications (optional)'
    required: false
  allure_results_path:
    description: 'Path to the directory containing Allure results'
    required: true
  retries:
    description: 'Number of previous test runs to show as retries in new test report (Default 0)'
    required: false
    default: 0
  show_history:
    description: 'Show history in the test report (true/false)'
    default: 'true'
  prefix:
    description: 'The storage bucket path to back up Allure results and history files'
    required: false
  update_pr:
    description: 'Add report info (url and status) as pull request comment or actions summary'
    default: 'summary'

outputs:
  report_url:
    description: 'URL to your test report'