name: Build CLI
on:
  workflow_dispatch:

jobs:
  deploy-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.5
      - name: Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: |
          npm install --workspace=@allure/cli

      - name: Run test
        run: npm run test --workspace=packages/cli

      - name: Compile JS
        run: npm run build --workspace=packages/cli

      - name: NPM Publish
        uses: JS-DevTools/npm-publish@v3.1.1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: packages/cli

  deploy-shared:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.5
      - name: Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: |
          npm install --workspace=allure-deployer-shared
      - name: Run test
        run: npm run test --workspaces

      - name: Compile JS
        run: npm run build --workspace=packages/shared

      - name: NPM Publish
        uses: JS-DevTools/npm-publish@v3.1.1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: packages/shared