name: Build GitHub Action
on:
  workflow_dispatch:
    inputs:
      semver:
        description: Bump version
        required: true
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  deploy-docker-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.5
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6.10.0
        with:
          context: .
          file: ./packages/action/action.Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            sokari/allure-deployer-action:latest
            sokari/allure-deployer-action:${{ github.sha }}
