name: Build GitHub Action
on:
  workflow_dispatch:

jobs:
  deploy-docker-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.5
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install deps
        run: |
          npm install --workspace=allure-deployer-shared
          npm install --workspace=@allure/action

      - name: Run test
        run: npm run test --workspaces

      - name: Compile JS
        run: |
          npm run build --workspace=packages/shared
          npm run build --workspace=packages/action

      - name: Remove dev deps
        run: |
          npm install --workspace=allure-deployer-shared --omit=dev
          npm install --workspace=@allure/action --omit=dev

      - name: Build and push
        uses: docker/build-push-action@v6.10.0
        with:
          context: .
          file: action.Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            sokari/allure-deployer-action:latest
            sokari/allure-deployer-action:${{ github.sha }}
