name: Test Docker
on:
  workflow_dispatch:
    inputs:
      retries:
        description: 'Number of test runs to show as retries in report'
        default: '10'
      show-history:
        description: 'Show keep history in report'
        type: boolean
        default: true
      report-name:
        description: 'Title of the report'
        required: false
        default: 'Allure Report'
jobs:
  test-docker:
    runs-on: ubuntu-latest
    env:
      GCP_SECRETS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
    steps:
      - uses: actions/checkout@v4.1.5
      - name: Run Tests
        run: |
          echo 'No test to run, using existing assets/allure-results from this repository'

      - name: Write GCP Credentials
        run: |
          echo "$GCP_SECRETS" > ${{ github.workspace }}/gcp-key.json

      - name: Authenticate Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Deploy Allure Report to Firebase
        run: |
          docker run --rm \
          -e STORAGE_BUCKET=${{vars.STORAGE_BUCKET}} \
          -e RETRIES=${{ github.event.inputs.retries }} \
          -e SHOW_HISTORY=${{ github.event.inputs.show-history }} \
          -e SLACK_TOKEN=${{secrets.SLACK_TOKEN}} \
          -e SLACK_CHANNEL=${{secrets.SLACK_CHANNEL_ID}} \
          -v ${{ github.workspace }}/assets/allure-results:/allure-results \
          -v ${{ github.workspace }}/gcp-key.json:/credentials/key.json \
          sokari/allure-deployer:latest